POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "product 2",
    "description": "basic desc",
    "image_url": "https://via.placeholder.com/150",
    "price": 100
}

###

GET http://localhost:3000/products

###

GET http://localhost:3000/products/b14d6912-a1bc-4cd7-a5e5-3b00cd1da7d1

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "items":[
        {
            "product_id": "07f452b0-954d-4086-80e7-e208adc5ea72",
            "quantity": ""
        },
        {
            "product_id": "fde79bca-3151-4a29-8eab-00fd1759e851",
            "quantity": 3
        }
    ],
    "card-hash": "123"  
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "chris",
    "password": "chris"
}

### auth with token
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDY5MDY5MzksImV4cCI6MTcwNjkwNjk5OX0.CAQY1QeZ62SjUXcesghcvrXnWXh4JIsggF7cz2F_3fk